language: python
python:
  - 2.7
  - 3.3
  - 3.4

sudo: false

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    
notifications:
  email:
    - pohl@physik.uni-bonn.de

install:
  - travis_wait pip install -r requirements.txt
  - python setup.py install

# Run test
script: nosetests
