language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    
notifications:
  email:
    - pohl@physik.uni-bonn.de

#before_install:
  #- if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  #- chmod +x miniconda.sh
  #- bash miniconda.sh -b -p $HOME/miniconda
  #- export PATH="$HOME/miniconda/bin:$PATH"
  #- conda update --yes conda

install:
  - travis_wait pip install -r requirements.txt --download-cache $HOME/.pip-cache
  - python setup.py install

# Run test
script: nosetests
