language: python
python:
  - 2.7
sudo: false
branches:
  only:
    - master
notifications:
  email:
    - pohl@physik.uni-bonn.de
 
# Setup miniconda with needed packages in a new virtual test-environment
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda create --yes -n test-environment numpy cython nose
  - source activate test-environment

# Install pybar with needed packages
install:
  # Install pyLandau
  - python setup.py install

# Run test
script:
- nosetests
