language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

sudo: false

notifications:
  email:
    - pohl@physik.uni-bonn.de

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
	  wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
	else
	  wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
	fi
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - pip install -r requirements.txt
  - python setup.py install

# Run test
script: nosetests
