name: Build wheels

on: workflow_dispatch
  # release

jobs:
  build_wheels:
    name: Build wheels on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
    - uses: actions/checkout@v2

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.3.0
      with:
        output-dir: wheels
      env:
        CIBW_ARCHS: auto64  # Build 64bit versions only
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_BUILD: cp37-* cp38-* cp39-*  # Build on CPython 3.7 - 3.9 only for now
        CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7"
        CIBW_SKIP: cp37-musllinux* cp38-musllinux* cp39-musllinux*
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_TEST_COMMAND: "echo Wheel installed"

    - uses: actions/upload-artifact@v2
      with:
        path: ./wheels/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          cache: 'pip'

      - name: Install build module
        run: python -m pip install build setuptools

      - name: Build sdist
        run: python -m build --sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
